hydra:
  searchpath:
    - file://verl/trainer/config

defaults:
  - ppo_trainer
  - _self_

# ============= 完全异步训练配置 (Fully Async Training Config) =============

async_training:
  # 新鲜度控制 (Freshness Control)
  staleness_threshold: 1              # 样本新鲜度阈值
  trigger_parameter_sync_step: 4     # >=1 train 每次训练一个batch, 迭代多少次后触发更新
  partial_rollout: True               # 同步参数时，是否中断 rollout
  use_rollout_log_probs: True

# Rollout配置
rollout:
  nnodes: 1                          # Number of nodes used in the rollout
  n_gpus_per_node: 8                 # Number of GPUs per node
  n: 4                               # 每个prompt生成的响应数量
  total_rollout_steps: 100
  total_epochs: 10
  test_freq: 1                       # 测试频率, 每多少次参数更新后进行一次测试

data:
  gen_batch_size: 32
